services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    env_file: .env
    volumes:
      - ./:/config/qBittorrent
      - ../flexget/data:/flexget
      - /home/my-user/files/downloads:/downloads
    ports:
      - 8081:8081
      - 56728:56728
      - 56728:56728/udp
    restart: unless-stopped

networks:
  default:
    name: caddy_net
    external: true