services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./:/etc/caddy
      - ./caddy_data:/data/caddy
      - ./caddy_config:/config/caddy

networks:
  default:
    name: caddy_net
    external: true