services:
  autobrr:
    image: ghcr.io/autobrr/autobrr:latest
    container_name: autobrr
    env_file: .env
    user: $PUID:$PGID
    volumes:
      - ./autobrr:/config
    ports:
      - 7474:7474
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    env_file: .env
    volumes:
      - ./prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

networks:
  default:
    name: caddy_net
    external: true