services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    env_file: .env
    restart: unless-stopped

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    env_file: .env
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - ./:/config
      - /lib/modules:/lib/modules
    dns:
      - $CUSTOMDNS
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped